# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fred062f-github-microservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8e3ee159d4954d5d8e75c59ae4564bf8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_35bc8e0487f8422793b331a1ef2df2f0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8e3ee159d4954d5d8e75c59ae4564bf8 }}/github_microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fred062f-github-microservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_48298693baaf4b5fa8c19b46e452f749 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8e3ee159d4954d5d8e75c59ae4564bf8 }}/github_microservice:${{ github.sha }}'